### ISSUE TITLE
Klarna payment - not having the correct order number.

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop1.7#503] opened 2022-01-12 08:56 UTC
### Expected behavior
The ordernumber field in the backoffice of Mollie should have the same orderid that is in the backoffice of Prestashop.

### Actual behavior
Klarnapayment is created but still having the temporary ordernumber ID when the order is paid.

![klarna-payment-method](https://user-images.githubusercontent.com/49270150/149095193-7362c251-9d86-4d9b-9210-379843786874.png)

### Steps to reproduce the behavior
Created an order with klarna payment method and complete the order.

### Environment
* PrestaShop version: 1.7.8.2
* Mollie module version: 4.4.3
* PHP version: 7.2.34

**Comment by loonas** [comment] 2022-01-13 10:59
Hi @Maikel726,

I hope that you are doing well today! Thank you for reaching out to us.
I have forwarded the issue to the developer, and we will keep you updated about the progress.

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-01-13 13:30
Hi @Maikel726,

Could you let us know the shop's URL? It might not work due to Mollie seeing it as a local shop, which is fixed on the upcoming release, but to be sure that that's the cause, a shop URL would be needed.

In the next planned release, a webhook URL will be added even in localhost and other dev shops.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Maikel726** [comment] 2022-01-13 13:38
Hi,

The URL is: https://www.autotravelshop.nl/.

**Comment by loonas** [comment] 2022-01-13 13:55
Thank you @Maikel726!

I have forwarded it to the developer and we will check it out further. We will let you know as soon as possible.

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-01-13 15:54
Hi @Maikel726,

It seems that the issue could have been raised by a different cause. Could you provide us a screenshot of the Mollie.com history, if any webhook errors appeared? BO credentials would help us investigate as well, you can send them directly to support@invertus.eu.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-01-14 12:55
Hi @Maikel726,

As we have discussed via email, our developer has looked into the details, and right now we were unable to reproduce the issue.
Based on all of the information provided, it's highly possible that our newest release will resolve this, as a lot of improvements have been made.

The upcoming release beta version launch is planned for January 20th. We will additionally let you know once it is released!

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-01-20 08:18
Hi @OguzhanLevent,

As the fix will be included in the upcoming release, we are closing the ticket for now, and we will let you know once the new version is launched.

Thank you for your understanding!

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-01-20 08:19
Hi @Maikel726,

As the fix will be included in the upcoming release, we are closing the ticket for now, and we will let you know once the new version is launched.

Thank you for your understanding!

Best regards,
Invertus Support team

**Closed by loonas** 2022-01-20 08:18 UTC
Labels: Release: Upcoming release

**Comment by loonas** [comment] 2022-01-25 12:16
Hi @Maikel726,

I hope that you are doing well! Thank you for your patience.

The issue has been resolved in the new release, which has the beta version out, and can be downloaded here - https://github.com/mollie/PrestaShop1.7/releases/tag/v5.0.0-beta1

Let us know if you have any other questions, and any feedback regarding the release!

Best regards,
Invertus Support team
