### ISSUE TITLE
Mollie creates other order amount after paying order (on order creation)

### ISSUE THREAD

**Issue by RVanDamage** [mollie/PrestaShop1.7#510] opened 2022-01-19 12:04 UTC
### Behavior
1. Total order amount in cart (check out) is OK
2. When going to Mollie actual payment page (PayPal, iDeal, etc.) amount is also OK
3. After making payment and being redirected back to PrestaShop order confirmation page, the order is placed with different amount.

We tested this issue extensively. This issue started from Mollie module version 4.4.x
Solved for now by switching back to module version 4.3.3 (but this version has the order creation before actual paying problem :()

### Steps to reproduce the behavior
On email I can provide dev location of shop, front-end user login to create own order, and backoffice and other credentials to check it out. Luckily we can reproduce this issue also when Mollie module is on testing API.

### Environment
* PrestaShop version: 1.7.7.7 
* Mollie module version: 4.4.3 
* PHP version: 7.3.33

**Comment by loonas** [comment] 2022-01-19 12:27
Hi @RVanDamage,

I hope that you are doing well. Thank you for reaching out to us regarding this issue!

In order for our developer to check it out, could you provide your BO+FTP credentials to support@invertus.eu? 
Additionally, order reference number and order history on Mollie, as well as the screenshots of the the issue of where the different amount appears would be appreciated.

We will be looking forward to your reply!

Best regards,
Invertus Support team

**Comment by RVanDamage** [comment] 2022-01-19 13:22
Hi @loonas,

Thanks for the quick reply.
We're on it!

**Comment by loonas** [comment] 2022-01-19 14:00
Thank you for your reply @RVanDamage! Great to hear that!

We will be looking forward to the details via email in this case, so our team could look into it for you :)

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-01-20 17:07
Hi @RVanDamage, 

Thank you for your patience! 

Our developer has looked into the issue and it seems that the issue is related to theme or module.

By default, Prestashop takes default group and its' discount - in this case the default group is WAYFAIR, that has 0% discount, and it also has group access to discount10, that gives 10% discount.

By default, Prestashop should give the 0%, as it's the default group, and usually works on default modifications, but it seems that on this store is adding the best discount for the product, but when we try to create order that the old default logic works and it doesn't find the discount. This is more related to theme, or module issue with Prestashop itself.
Mollie only calls the default order creation, and it is up to Prestashop to create it.

Let me know if you have any further questions!

Best regards,
Augustė

**Comment by RVanDamage** [comment] 2022-01-20 17:24
Hi @loonas,

No problem.

And of course, I understand your developer. At first I thought it was related to the special groups too. Because the difference in total amount was exactly the 10% group discount amount. However it's not!
Indeed this example happend to be a customer with discount and assigned to special customer groups.
But this issue also happens for customers that have no special customer groups or discounts applied. So for a regular customer.

I will email more examples.

Kind regards,
R

**Comment by RVanDamage** [comment] 2022-01-21 08:38
Hi @loonas,

Indeed we have an override related to applying the discount, but even if, why does Mollie not take it into account? It should ask the PrestaShop code about the final prices, and that code should be also part of it. It looks like it must be calculating something on it's own, assuming some default logic, but not using the actual logic that is there...

**Comment by loonas** [comment] 2022-01-21 12:36
Thank you for your reply and the further details @RVanDamage!

I have forwarded the additional details and your questions to our developer, so that they could look into it, and provide more information.
We will keep you updated!

Additionally, if you could share additional examples via email, it would be appreciated, as it would help us investigate.

Best regards,
Invertus Support team

**Comment by wzzly** [comment] 2022-01-24 18:54
@RVanDamage @loonas 
I have the exact same problem. We use a module to set vat to 0% for customers (companies) with a verified EU vat-number. The module checks the vat-number with VIES and when verified, removes the vat from the order. Then the customer pays the order with mollie, which also works. But then an order is created by prestashop WITH vat and gives an error in the BO order page, that only part of the order total is paid (vat is not paid offcourse).
See attachement.

![image](https://user-images.githubusercontent.com/35727938/150845906-48eead62-c418-4780-b4d5-41bdfa7307fd.png)

**Comment by wzzly** [comment] 2022-01-24 18:57
it's this module by the way:
https://addons.prestashop.com/nl/bestelproces/49318-company-verification-in-the-vies-system.html

It's one of the few modules for this, so a lot of shops must use this as it is mandatory to set vat to 0% for EU companies (that are located in another EU country then the shop) and prestashop doesn't have a native feature for this.

**Comment by wzzly** [comment] 2022-01-24 19:08
Made a test order with vat-number (0%) and paid the order with other payment method then Mollie and then the order gets created correctly without vat.
![image](https://user-images.githubusercontent.com/35727938/150848015-7818d4d7-5695-4dac-8eca-a0fdcb94f617.png)

**Comment by RVanDamage** [comment] 2022-01-24 21:20
Hi @wzzly,

We would tell you to revert back to Mollie 4.3.3 but unfortunately Mollie 4.3.3 has this VAT issue too. Not sure wether it's related to our issue above.

We discovered this VAT issue also when using 4.4.3 while it was an updated version of 4.3.3
However, we did some more testing on a clean 4.4.3 Mollie, meaning we removed old version (4.3.3) fully including database tables with prefix mol_ and one is mollie_ which results in not being able to reproduce this VAT issue again.
Our question to you is do you come from an updated version as well?

Regardless, the issue above remains, also on clean version of Mollie 4.4.3
Like we said, Mollie module should ask the PrestaShop code about the final prices. Currently it looks like their module is calculating something on it's own, assuming some default logic, but not using the actual logic that is there...

We will provide them with more examples asap, but at the moment we are just too busy :(

**Comment by jponabehere** [comment] 2022-01-25 09:16
Hi all,

I am working on a similar case for a merchant in which we wants VAT to not be applied when certain conditions are met:

Customers should always pay VAT, unless they match all of the conditions below (not just one, but all of them):

They are member of the customer group “Shopkeeper”
Their address is based in Europe (so that’s why we used Portugal as an example)
Their address is NOT based in Belgium (because that would be the same country as Fibre Mood).

In order to accomplish this they did modify some code in a default PrestaShop file:
VAT rules were added in this (default prestashop) file: /var/web/vd18046/public_html/classes/tax/TaxCalculator.php

Everything on the frontend works OK, if all conditions are met, the consumer does not pay tax but after the payment is done in the backend the order is created with VAT therefore causing a mismatch and the order status becomes ""

So the same as reported initially:
1. Total order amount in cart (check out) is OK
2. When going to Mollie actual payment page (PayPal, iDeal, etc.) amount is also OK
3. After making payment and being redirected back to PrestaShop order confirmation page also OK
4. The order created in the backend shows a different amount (with tax).

An example below:
Product is €12.50 tax included, but the merchant paid €11.83 (€10.33 product tax excluded + shipping)

![image](https://user-images.githubusercontent.com/93710191/150944419-566ad70b-5a94-4c39-b83e-3c158e24d5dc.png)

![image](https://user-images.githubusercontent.com/93710191/150944464-511fe6da-cd35-415c-9228-63aeae50f950.png)

![image](https://user-images.githubusercontent.com/93710191/150944505-be8701ca-fd52-448f-841b-46e3a18d3f38.png)

This only happens for orders with Mollie payments, for standard PrestaShop bank transfer for instance it works fine.

**Comment by wzzly** [comment] 2022-01-25 11:22
@jponabehere  yes seems like the same problem. The problem has something to do with the process that mollie triggers after a succesfull payment (order creation). It's not taking into account the total cart amount before payment.

**Comment by loonas** [comment] 2022-01-25 11:27
Hello @RVanDamage @wzzly @jponabehere,

Thank you for the additional details and your interest in perfecting the Mollie module.
I have forwarded all of the mentioned information for our developer to check out, if these situations are related, and investigate further based on the new information.

Once we have any updates, we will let you know!

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-01-25 14:53
Hello @RVanDamage @wzzly @jponabehere,

Our developer has looked into the newest details, and he has found the issue why VAT modules did not work correctly with Mollie. VAT module checks context for customer information, and the Webhook does not have it. Our developer has fixed this by adding it to the Webhook, so that the VAT module can retrieve it.

Our developer has included the fix for the newest release beta2 version, which will be available on January 31th.

Alternatively, the fix can be added manually by downloading [the latest release](https://github.com/mollie/PrestaShop1.7/releases/tag/v5.0.0-beta1) and adding [this fix](https://github.com/mollie/PrestaShop1.7/pull/516).

We will be looking forward to your feedback and questions!

Best regards,
Invertus Support team

**Comment by jponabehere** [comment] 2022-01-26 08:41
Hi @loonas,

That's great news! thanks!

**Comment by loonas** [comment] 2022-01-26 14:31
Thank you for your reply and the kind words @jponabehere!

We are more than happy to help :) We will keep the issue open for a few in case you have any questions or comments!

Best regards,
Invertus Support team

**Comment by jponabehere** [comment] 2022-01-26 14:42
Hi @loonas,

Just one more question, is it possible to provide Version 5.0.0-beta1 to a merchant? Or do we need to wait for the official release?

Thanks and regards!

**Comment by loonas** [comment] 2022-01-26 15:22
Thank you for your question @jponabehere!

The version 5.0.0-beta1 can be fully provided to the merchant, you can find it [here](https://github.com/mollie/PrestaShop1.7/releases/tag/v5.0.0-beta1) in our latest releases. 

Please note that the fix for this particular issue is not yet included, and in case of urgency, it can be included by manually applying [this fix](https://github.com/mollie/PrestaShop1.7/pull/516).

In case you have any troubles adding it manually, we will include this fix in version 5.0.0-beta2, which will be released January 31th. I'll additionally inform you once it is released as well!

If you have any further questions, we are here for you!

Best regards,
Invertus Support team

**Comment by RVanDamage** [comment] 2022-01-26 15:27
> Hello @RVanDamage @wzzly @jponabehere,
> 
> Our developer has looked into the newest details, and he has found the issue why VAT modules did not work correctly with Mollie. VAT module checks context for customer information, and the Webhook does not have it. Our developer has fixed this by adding it to the Webhook, so that the VAT module can retrieve it.
> 
> Our developer has included the fix for the newest release beta2 version, which will be available on January 31th.
> 
> Alternatively, the fix can be added manually by downloading [the latest release](https://github.com/mollie/PrestaShop1.7/releases/tag/v5.0.0-beta1) and adding [this fix](https://github.com/mollie/PrestaShop1.7/pull/516).
> 
> We will be looking forward to your feedback and questions!
> 
> Best regards, Invertus Support team


Hi @loonas,

Nice! So is only the VAT issue solved, or also the issue where Mollie is calculating something on it's own?
Because it should ask the PrestaShop code about the final prices...

**Comment by loonas** [comment] 2022-01-27 07:27
Thank you for the question @RVanDamage!

I have consulted this with our developer, and the issue was more due to the Prestashop logic with VAT, rather than Mollie calculating something on it's own. 
Mollie does ask Prestashop code regarding the final prices, and the fix was applied to the webhook directly.

Let me know if you have any further questions regarding this issue!

Best regards,
Invertus Support team

**Comment by RVanDamage** [comment] 2022-01-27 07:35
@loonas Ok thanks. We will try it out, and if we run into other issues we'll get back to you.

**Comment by loonas** [comment] 2022-01-27 10:05
@RVanDamage we are always happy to help!

We will be looking forward to your comments or questions, so if anything comes up, please do let us know :)

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-02-01 08:16
Hi,

Due to inactivity, I will mark this issue as resolved. Let us know if you will have any other questions!

Best regards,
Invertus Support team

**Comment by jponabehere** [comment] 2022-02-01 08:25
Hi @loonas,

When will version 5.0.0-beta2 including this [fix](https://github.com/mollie/PrestaShop1.7/pull/516) be released?

**Comment by loonas** [comment] 2022-02-01 09:09
Hi @jponabehere,

We are planning it's release for this week. I will ping you here in this issue once the beta2 version is available :)

If you have any further questions, let us know!

Best regards,
Invertus Support team

**Comment by jponabehere** [comment] 2022-02-02 11:23
Thanks @loonas!!

**Comment by RVanDamage** [comment] 2022-02-02 11:38
Thanks @loonas! We just installed it clean on our customers live shop. Curious how it goes :)

**Comment by loonas** [comment] 2022-02-02 16:50
Always happy to help @jponabehere @RVanDamage!

In case you run into any issues or questions, feel free to reach out to us!

Best regards,
Invertus Support team

**Comment by RVanDamage** [comment] 2022-02-07 20:22
Hi @loonas,

It looked like it was fully fixed in the new 5.0.0-beta2 version, however two days ago our customer received a new order with no VAT calculated. No VAT at all this time. Not like before where there was VAT in the placed order, but just not being actually payed.

When I check back office I see that customer had a cart (including 21% VAT) right before placing the actual order:

![Unknown](https://user-images.githubusercontent.com/68848292/152865412-53d3430e-7dec-4471-b206-6947cdd855ff.png)

**Comment by loonas** [comment] 2022-02-09 13:24
Hi @RVanDamage! Thank you for your feedback!

I have forwarded these details to the developer to check further. We will let you know regarding the progress of the issue, and if any additional details will be necessary.

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-02-17 12:01
Hi @RVanDamage! Hope that you are doing well.

Our developer has checked the details and could not reproduce the issue, so more information would be needed.
In case you could share BO+FTP credentials of the affected shop, it would help a lot - you can send them to support@invertus.eu if possible.

Additionally, it would be good if you could clarify what VAT module is used and any additional information, as there are a lot of VAT modules and it is difficult to check if VAT needs to be paid.

We will be looking forward to your reply!

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-02-23 09:03
Hi @RVanDamage! How are you today?

Due to inactivity, I will mark this issue as resolved. Let us know once you would like to proceed!

Best regards,
Invertus Support team

**Comment by RVanDamage** [comment] 2022-03-09 09:52
Hi @loonas,

Can we reopen this ticket?

Our customer would like to continue and solve this issue. We can share BO+FTP, and also we have 3 example (Mollie) orders where the VAT is not being calculated. It's not easy to reproduce issue. But we can however explain exactly how our VAT is altered. It's not with a module but with custom coding, and it's done the right way.

Should we email all info to you?

Kind regards,
R

**Comment by loonas** [comment] 2022-03-09 14:15
Hi @RVanDamage! Hope that you are doing well!

Of course, the ticket can be re-opened. I have re-opened it now - in order to proceed with the investigation, could you share the mentioned details (BO+FTP as well as the 3 order examples) to support@invertus.eu?
Please make sure to include the details regarding how VAT is being altered with custom coding as well.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by RVanDamage** [comment] 2022-03-09 15:02
Hi @loonas,

Thanks fort he quick reply and re-opening the ticket.

I just provided all the needed info in an email to support@invertus.eu

**How we custom coded the VAT proces:**

1. The Customer object is extended to have a vat_amount field, which is simply stored in the database table along with each customer, so each customer has an individual VAT amount assigned.

2. An Override is created for the TaxCalculator::getTotalRate function, which replaces it with reading this field, or returning a default rate of 21 in case current customer is unknown.

**Comment by loonas** [comment] 2022-03-09 15:16
Thank you @RVanDamage!

We have received the details and they have been forwarded to the team. We will keep you updated regarding the progress!

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-03-22 08:51
Hi @RVanDamage! Hope that you are doing well.

Our developer has checked the new details and unfortunately, was still unable to reproduce the issue.
He has tried creating 2 orders: 

- 1676
- 1677

He used delivery and the user [support@invertus.eu](mailto:support@invertus.eu), but the attempts brought the correct price all the time.

Could you create an order with the specified issue, so that the developer could try to re-order it and investigate?


Additionally, all extra information would be appreciated.

Best regards,
Invertus Support team

**Comment by loonas** [comment] 2022-03-28 08:53
Hi @RVanDamage! How are you today?

Due to inactivity, I will mark this issue as resolved. Let us know once you would like to proceed!

Best regards,
Invertus Support team

**Closed by loonas** 2022-03-28 08:53 UTC
Labels: Status: Additional Info Required, Type: Support
