### ISSUE TITLE
Order status changed to Mollie partially refunded while nothing has been refunded

### ISSUE THREAD

**Issue by melissaandries** [mollie/PrestaShop1.7#607] opened 2022-09-19 09:59 UTC
### Expected behavior
Status should not change

### Actual behavior
Order status is being changed to Mollie partially refunded while nothing has been refunded

### Steps to reproduce the behavior
We see this with random live orders, unable to reproduce as not sure what is triggering this issue

### Environment
* PrestaShop version:  1.7.8.5
* Mollie module version: v5.2.1 
* PHP version: 7.4.19<

**Comment by justelis22** [comment] 2022-09-19 10:00
Hey there @melissaandries,

We will be glad to help you with this! Our team will check your case, and get back to you as soon as possible with an update.

--
Best Regards,
Invertus Support team.

**Comment by melissaandries** [comment] 2022-09-19 12:43
Hi, 

I found the reason why this status was changed. Whenever a PayPal claim is being submitted, a chargeback request is created by Mollie and the status changes to partially refunded. Now, this shouldn't happen either as a PayPal claim doesn't automatically mean it should be refunded or has been refunded. 
Can you look into this?

Thanks again.

Krgds,
Melissa

**Comment by justelis22** [comment] 2022-09-19 14:38
Hi @melissaandries,

Is this related to all of the PayPal payments?

Please send us the transaction number, so we could investigate further.

--
Best Regards,
Invertus Support team.

**Comment by melissaandries** [comment] 2022-09-19 14:56
Hi,

I can see a few like these yes that are all PayPal.
Here you have two examples: tr_7Ud4mUuQaE & tr_Qmh2WR3zVu

**Comment by justelis22** [comment] 2022-09-20 11:26
Hey there @melissaandries!

We have communicated with the Mollie team, and it seems like they have identified the issue.
The issue is not caused by the module itself, as it is coming from the backend of the Mollie system, thus we would need to wait until it is fixed by the Mollie team.

We will keep you updated!

--
Best Regards,
Invertus Support team.

**Comment by melissaandries** [comment] 2022-09-20 13:30
Hi,

good to hear, thanks for the update! 

Krgds,
Melissa

**Comment by justelis22** [comment] 2022-09-20 13:57
@melissaandries,

It seems like the module is also related to this, we were able to replicate the issue. 
We are going to investigate the issue on a priority basis.

As soon as we have an update, we will let you know!

--
Best Regards,
Invertus Support team.

**Comment by melissaandries** [comment] 2022-10-03 11:08
Hi, do you have an update on this issue? We are still seeing this issue with our orders and it's even affecting orders that have not been fulfilled yet.
Thanks.

Krgds,
Melissa

**Comment by justelis22** [comment] 2022-10-04 13:22
Hi there @melissaandries,
Thanks for waiting!

We have identified and fixed the issue. At the moment, the bug fix is in testing, we will inform you about the progress.

--
Best Regards,
Invertus Support team.

**Comment by melissaandries** [comment] 2022-10-07 10:02
Hi there, 

sorry to say at our end we can still see this issue. 

![image](https://user-images.githubusercontent.com/105208007/194528336-4d4a7d4f-3102-44b5-b09e-c4809648c674.png)

Kind regards,
Melissa

**Comment by justelis22** [comment] 2022-10-07 10:38
Hi @melissaandries,

We completely understand that this must be inconvenient for you, although, no need to worry, we will be releasing a fix for this issue next week.

We value your patience and understanding!

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2022-10-18 14:51
Hi there,
I hope you are doing alright!

We just wanted to let you know that we have released the [5.3.0 beta version](https://github.com/mollie/PrestaShop1.7/releases). We have fixed the issue reported by you, so we would recommend updating the module.

If you find any issues or have some feedback, let us know!

--
Best Regards,
Invertus Support team.

**Closed** 2022-11-09 07:53 UTC
