### ISSUE TITLE
Mollie v5.1.0 - Payments received, but no created orders

### ISSUE THREAD

**Issue by RVanDamage** [mollie/PrestaShop1.7#597] opened 2022-07-25 13:21 UTC
Hi there,

One of our customers started noticing payed transactions in Mollie Dashboard but no created orders.
Luckily we can always see the cart ID's.

We looked them up in Presta backoffice, and indeed 3 customers found with abandoned cart's and no orders.
For now we created the orders manually, but we would like to know the cause of this.
Most of our customers don't run on module v5.1.0 yet, so it might have to do with this version.

Here's the transaction ID's of those 3 payments:
tr_4eJxVbgtak
tr_NDAR78JoNc
tr_vhc7AdwAU2

### Environment
* PrestaShop version: 1.7.8.2 
* Mollie module version: v5.1.0
* PHP version: 7.4.30

**Comment by justelis22** [comment] 2022-07-25 13:23
Hey there, @RVanDamage!

We have received your request, our team will overview the provided information, and we will get back to you!

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2022-07-25 13:47
@RVanDamage,

Could you please send us BO+FTP+SSH access to support@invertus.eu so that we could investigate the case further?
Waiting for your message!

--
Best Regards,
Invertus Support team.

**Comment by RVanDamage** [comment] 2022-07-25 14:13
Hi @justelis22,

Thanks for replying at such short notice.
We just shared the above asked credentials with you. Please confirm or you received our email.

**Comment by justelis22** [comment] 2022-07-25 14:16
@RVanDamage,

We have received the information, as soon as we have some details, we will get back to you!

--
Best Regards,
Invertus Support team.

**Comment by Maikel726** [comment] 2022-07-27 07:41
Hi,

Can confirm this is still an issue made an ticket for it a few weeks ago.

https://github.com/mollie/PrestaShop1.7/issues/547

**Comment by RVanDamage** [comment] 2022-07-27 07:52
Hi @Maikel726,

For us too :(
If I may ask. What version of the Mollie module do you use?
And do you happen to use a One Page Checkout module of some kind?

**Comment by Maikel726** [comment] 2022-07-28 07:41
hi @RVanDamage 

We use the latest version of the Mollie module, there is an 3th party One page checkout module.

**Comment by RVanDamage** [comment] 2022-07-28 07:53
Hi @Maikel726,

What OPC module do you use?
I have a strong feeling it might be the combination of OPC module in combination with Mollie module v5.1.0 and later.

**Comment by Maikel726** [comment] 2022-07-28 08:46
Hi @RVanDamage 

One Page Supercheckout from Knowband, Normally it works well but sometimes things don't go quite right with creating orders in the back office.

**Comment by justelis22** [comment] 2022-08-02 15:02
Hey there, @RVanDamage @Maikel726!
Thanks for waiting!

Our team has investigated the issue and implemented a fix, that should help to avoid issues with order creation.
Please try to upgrade your version to the latest 5.2.1 - https://github.com/mollie/PrestaShop1.7/releases

We have also tested the module with One Page Supercheckout from Knowband. It seems to get stuck at 80% most of the time, but if the checkout module does work successfully, the order is created without any issues.

We will be waiting for your feedback!

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2022-08-03 08:58
Hi, @RVanDamage,

While testing Mollie with the One Page Supercheckout module, we noticed that the one-page checkout module gets stuck at 80%. It does not seem like there are any issues with the Mollie module, as when the one-page checkout module works and loads to 100%, an order is created successfully.
So the module could be related to failed orders, we would suggest checking that out (testing orders without one-page checkout).

--
Best Regards,
Invertus Support team.

**Comment by Maikel726** [comment] 2022-08-03 11:43
Hi @RVanDamage

If the percentage remains stuck at 80% just contact the developers of the One Page checkout.

**Comment by justelis22** [comment] 2022-08-09 07:56
Hey there everyone!

As the issue was not updated for some time now, we are going to mark it as resolved.
Although, if you have some feedback, don't hesitate to leave it here!

--
Best Regards,
Invertus Support team.

**Comment by RVanDamage** [comment] 2022-08-22 17:36
Hi there @justelis22,

Opening issue again. Our customer had a new payment in Mollie dashboard, but no created order.
The cart was stuck again. For example cart ID 558.
Even though we updated module version to 5.2.1 

The provided credentials (28 days ago) should still work.
Is there anything else needed?

Kind regards,
R

**Comment by justelis22** [comment] 2022-08-23 06:28
Hey there @RVanDamage!

We will check, and let you know what could be causing the issue.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2022-08-23 10:11
Hi, @RVanDamage,

Our developer has checked, and it seems like the security key issue is preventing some orders to get created. 
We have already changed how the key is generated in 5.3.0, but this release has not been made yet. We could send you a beta version, or you can comment out mollie/src/service/TransactionService.php lines: 135-137 and 168-170, although, we must note that this approach reduces security.
While checking further we have noticed that the issue is happening only in your shop, as the secure key of the cart is being changed, when it should not, this could be caused by custom modules or the theme.
We will stop using PrestaShop secure key all along in the new release, so there should not be any issues.

If you would like to get the beta version, email us at support@invertus.eu

--
Best Regards,
Invertus Support team.

**Comment by RVanDamage** [comment] 2022-08-24 08:30
Hi @justelis22,

Thank you for the quick response, and good explanation.
When can we expect release 5.3.0 ?

**Comment by justelis22** [comment] 2022-08-24 09:31
Hello @RVanDamage!

The new release is expected in the middle of September.

If you have any questions, don't hesitate to ask!

--
Best Regards,
Invertus Support team.

**Comment by mariuszsienkiewicz** [comment] 2022-10-05 10:08
On one client's site, this problem also occurs. Also, it can be rather considered that this problem is bigger and it occurs in more cases.

I checked the logs and I couldn't find if your service even gave any information to PrestaShop that the payment was correctly processed.

To people who have the same problem, for the missing orders, I validate the payment manually so the module can create the order, so all you need is some REST client, you can even use the Advanced REST client extension for Google Chrome. Send a POST request to the /module/mollie/webhook endpoint, put in the request variables variable named "id" and as a value paste there the transaction id (I mean the one with this syntax - "tr_***") - module will validate the payment and create the order.

I'm looking forward to seeing the updated module or your service.

**Comment by justelis22** [comment] 2022-10-10 08:57
Hi @mariuszsienkiewicz,

The issue should be fixed on the new release, so we would like to ask you for some patience until we finish up with the testing and do the last touches.
The release is expected in the next couple of weeks.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2022-10-18 14:47
Hi there,
I hope you are doing alright!

We just wanted to let you know that we have released the [5.3.0 beta version](https://github.com/mollie/PrestaShop1.7/releases). We have fixed the issue reported by you, so we would recommend updating the module.

If you find any issues or have some feedback, let us know!

--
Best Regards,
Invertus Support team.

**Closed** 2022-11-09 07:52 UTC
