### ISSUE TITLE
Upgrade to v5.3.x from 5.2 crashes Prestashop 

### ISSUE THREAD

**Issue by elburgl69** [mollie/PrestaShop1.7#623] opened 2022-11-25 12:07 UTC
### Expected behavior
Mollie module upgraded to 5.3.x

### Actual behavior
Upgrading to v1.3.x  makes Pretashop crash with error:
`RuntimeException in CheckDefinitionValidityPass.php line 69:
The definition for "_defaults" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.`

### Steps to reproduce the behavior
Click upgrade button at the Mollie Module in the installed modules page in the back-end

### Environment
* PrestaShop version: 1.7.2.4 
* Mollie module version: 5.3.1
* PHP version: 7.1.33

### Work arround
Delete Mollie folder in modules.
Install Mollie version 5.2.1

**Comment by justelis22** [comment] 2022-11-25 14:35
Hi there @elburgl69,

Thank you for bringing this to our attention.
We will check, and get back to you with an update as soon as possible.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2023-03-07 10:27
@elburgl69 Hey there,

The issue is fixed with the latest releases, so if someone is still using the 5.2 version, we would suggest upgrading to the latest one manually and there will be no such issue in the future.

If anything, we will be waiting for your feedback!

Best Regards,
Invertus Support team.

**Closed by justelis22** 2023-03-07 10:27 UTC
Labels: Type: Fix, Priority: Medium, Release: Upcoming release
